# Current Version: 1.0.2

name: Build & Release hezhijie0327/Geosite2Domain

on:
  schedule:
    - cron: "0 8,20 * * *" # UTC+8 04:00 / 16:00
  workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Step 1 - Checkout
              uses: actions/checkout@v3.1.0
            - name: Step 2 - Setup Go Environment
              uses: actions/setup-go@v5
            - name: Step 3 - Build Geosite2Domain
              run: |
                  git clone https://github.com/v2fly/domain-list-community.git
                  cd domain-list-community
                  go mod download
                  export EXPORT_LISTS=$(ls -1 data | grep 'category-' | tr '\n' ',' | sed 's/,$//')
                  go run ./ --datapath=./data --outputdir=../ --exportlists=${EXPORT_LISTS}
                  cd ..
                  rm -rf domain-list-community *.dat
            - name: Step 4 - Release Geosite2Domain
              run: |
                  curl -s "https://raw.githubusercontent.com/hezhijie0327/Toolkit/main/Git.sh" > "/tmp/Git.sh"
                  sudo bash "/tmp/Git.sh" -u "hezhijie0327" -e "hezhijie0327@hotmail.com" -f "." -r "Geosite2Domain" -i "Generated by GitHub Actions" -m "push"
